2022-05-28 13:10:24,780 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:43]
2022-05-29 21:06:50,428 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:43]
2022-05-29 21:07:25,230 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:43]
2022-05-29 21:09:39,357 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:43]
2022-05-29 21:14:16,100 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:43]
2022-05-29 21:14:27,709 ERROR: Exception on /follow/Liam [POST] [in c:\repos\project1\project1\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\repos\project1\project1\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\repos\project1\project1\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\repos\project1\project1\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\repos\project1\project1\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\repos\project1\project1\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\repos\project1\project1\app\routes.py", line 108, in follow
    db.session.commit()
  File "<string>", line 2, in commit
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1435, in commit
    self._transaction.commit(_to_root=self.future)
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3367, in flush
    self._flush(objects)
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3507, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3467, in _flush
    flush_context.execute()
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 579, in execute
    self.dependency_processor.process_saves(uow, states)
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\dependency.py", line 1182, in process_saves
    self._run_crud(
  File "c:\repos\project1\project1\venv\lib\site-packages\sqlalchemy\orm\dependency.py", line 1207, in _run_crud
    raise exc.StaleDataError(
sqlalchemy.orm.exc.StaleDataError: DELETE statement on table 'followers' expected to delete 1 row(s); Only 0 were matched.
2022-05-29 21:23:00,394 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:43]
2022-05-29 21:23:06,733 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:43]
2022-05-29 21:32:23,980 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:43]
2022-05-29 21:38:29,779 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:43]
2022-05-29 21:59:25,378 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:45]
2022-05-29 22:00:59,244 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:45]
2022-05-29 22:09:11,916 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:45]
2022-05-29 22:18:07,264 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:45]
2022-06-04 15:18:54,849 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:48]
2022-06-04 15:27:02,473 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:50]
2022-06-06 14:34:17,339 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:51]
2022-06-06 21:41:36,952 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:51]
2022-06-06 21:47:42,518 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:51]
2022-06-06 21:57:39,160 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:51]
2022-06-06 21:59:38,014 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:51]
2022-06-07 10:43:51,961 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:74]
2022-06-07 10:43:56,452 ERROR: Exception on /index [GET] [in c:\repos\project1\project1\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\repos\project1\project1\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\repos\project1\project1\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\repos\project1\project1\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\repos\project1\project1\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\repos\project1\project1\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\repos\project1\project1\app\main\routes.py", line 37, in index
    posts = current_user.followed_posts().paginate(page, app.config['POSTS_PER_PAGE'], False)
NameError: name 'app' is not defined
2022-06-07 10:45:31,801 INFO: Microblog startup [in C:\repos\project1\project1\app\__init__.py:74]
